version: '3.4'
services:
  node_portal:
    build:
      dockerfile: ./node.Dockerfile
      context: .
    image: node_portal
    container_name: node_portal
    restart: always
    ports:
      - "2124:3000"
    networks:
      - portal-network
    # depends_on:
    #   - mongodb

  mongodb:
    image: mongo
    restart: always
    networks:
      - portal-network

networks:
  portal-network:
    driver: bridge
